### PR TITLE
fix(deps): update dependency mendix to ^9.24.2965

### PR DESCRIPTION
**Pull request by uicontent**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| mendix | dependencies | minor | [`^9.23.621` -> `^9.24.2965`](https://renovatebot.com/diffs/npm/mendix/9.23.621/9.24.2965) |
| mendix | devDependencies | minor | [`^9.23.621` -> `^9.24.2965`](https://renovatebot.com/diffs/npm/mendix/9.23.621/9.24.2965) |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by uicontent** [comment]
### Edited/Blocked Notification

Renovate will not automatically rebase this PR, because it does not recognize the last commit author and assumes somebody else may have edited the PR.

You can manually request rebase by checking the rebase/retry box above.

 ⚠ **Warning**: custom changes will be lost.

**Comment by iobuhov** [comment]
@tamelbrun, what the plan? Should we update this along with PWT or we can merge this update separately? As far as I can see there no type errors.

**Review by iobuhov — APPROVED** [review]
AS all green, let's merge it. All incidents will be fixed on the go.

**Comment by iobuhov** [comment]
cc: @leonardomendix , @gjulivan

**Pull request merged**
