### PR TITLE
chore(deps): update dependency @mendix/pluggable-widgets-tools to >=9.20.0

### PR DESCRIPTION
**Pull request by uicontent**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [@mendix/pluggable-widgets-tools](https://togithub.com/mendix/widgets-tools/tree/master/packages/pluggable-widgets-tools) ([source](https://togithub.com/mendix/widgets-tools)) | devDependencies | minor | [`>=9.0.0` -> `>=9.20.0`](https://renovatebot.com/diffs/npm/@mendix%2fpluggable-widgets-tools/9.0.0/9.20.0) |

---

### Release Notes

<details>
<summary>mendix/widgets-tools</summary>

### [`v9.20.0`](https://togithub.com/mendix/widgets-tools/compare/f13e53152a267cce38e9c693a8e907ce76d07b36...ae7de6daa32e8a6df9a3f5aca07f9cef2a263383)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/f13e53152a267cce38e9c693a8e907ce76d07b36...ae7de6daa32e8a6df9a3f5aca07f9cef2a263383)

### [`v9.18.0`](https://togithub.com/mendix/widgets-tools/compare/27f605433277f5832292ac480cd531f1968ebf49...f13e53152a267cce38e9c693a8e907ce76d07b36)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/27f605433277f5832292ac480cd531f1968ebf49...f13e53152a267cce38e9c693a8e907ce76d07b36)

### [`v9.17.0`](https://togithub.com/mendix/widgets-tools/compare/4e389bb280072a0baa44fe4a608011fa7e5ff45e...27f605433277f5832292ac480cd531f1968ebf49)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/4e389bb280072a0baa44fe4a608011fa7e5ff45e...27f605433277f5832292ac480cd531f1968ebf49)

### [`v9.13.4`](https://togithub.com/mendix/widgets-tools/compare/c6dddfb905c0e0b07ca45d3284b23b5e7b4f11a3...4e389bb280072a0baa44fe4a608011fa7e5ff45e)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/c6dddfb905c0e0b07ca45d3284b23b5e7b4f11a3...4e389bb280072a0baa44fe4a608011fa7e5ff45e)

### [`v9.13.3`](https://togithub.com/mendix/widgets-tools/compare/0b7785123ccf57c8e6c2d958482c16f8273caf97...c6dddfb905c0e0b07ca45d3284b23b5e7b4f11a3)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/0b7785123ccf57c8e6c2d958482c16f8273caf97...c6dddfb905c0e0b07ca45d3284b23b5e7b4f11a3)

### [`v9.13.2`](https://togithub.com/mendix/widgets-tools/compare/ef181ee8d68b77ec3ac18c58fd646b776b5d03bd...0b7785123ccf57c8e6c2d958482c16f8273caf97)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/ef181ee8d68b77ec3ac18c58fd646b776b5d03bd...0b7785123ccf57c8e6c2d958482c16f8273caf97)

### [`v9.13.1`](https://togithub.com/mendix/widgets-tools/compare/01e4f7158d2ea5207bcbaaab27a035bef633b37f...ef181ee8d68b77ec3ac18c58fd646b776b5d03bd)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/01e4f7158d2ea5207bcbaaab27a035bef633b37f...ef181ee8d68b77ec3ac18c58fd646b776b5d03bd)

### [`v9.13.0`](https://togithub.com/mendix/widgets-tools/compare/1bc25fc2076c0923080fe790131ba697695f0b04...01e4f7158d2ea5207bcbaaab27a035bef633b37f)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/1bc25fc2076c0923080fe790131ba697695f0b04...01e4f7158d2ea5207bcbaaab27a035bef633b37f)

### [`v9.11.1`](https://togithub.com/mendix/widgets-tools/compare/1e4dffa2d4ca06f2114e185e25b10a9985f1b3c4...1bc25fc2076c0923080fe790131ba697695f0b04)

[Compare Source](https://togithub.com/mendix/widgets-tools/compare/1e4dffa2d4ca06f2114e185e25b10a9985f1b3c4...1bc25fc2076c0923080fe790131ba697695f0b04)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by leonardomendix** [comment]
Not sure if that's a good idea to do that for this widget.

**Review by iobuhov — APPROVED** [review]

**Comment by iobuhov** [comment]
Or, we can just pin it to 9.0.0

**Review by rahmanunver — APPROVED** [review]

**Comment by iobuhov** [comment]
@leonardomendix, so, should we merge, or should we close this PR?

**Comment by leonardomendix** [comment]
@iobuhov  Hey! Let's close this one and pin that version, it doesn't worth updating since in the future we'll migrate it.

**Comment by uicontent** [comment]
### Renovate Ignore Notification

As this PR has been closed unmerged, Renovate will now ignore this update (>=9.20.0). You will still receive a PR once a newer version is released, so if you wish to permanently ignore this dependency, please add it to the `ignoreDeps` array of your renovate config.

If this PR was closed by mistake or you changed your mind, you can simply rename this PR and you will soon get a fresh replacement PR opened.

**Pull request closed without merging**
