### PR TITLE
[WC-2680] onChange not trigger on empty or not empty filter

### PR DESCRIPTION
**Pull request by gjulivan**
### Pull request type

---

### CODE REVIEW

**Review by samuelreichert — DISMISSED** [review]

**Review by iobuhov — CHANGES_REQUESTED** [review]
I think we should not use Math.random to trigger change...

**Comment by iobuhov** [comment]
I think it should be fixed on useBasicSync level. Just change line 26 from
```
return reaction(() => [store.arg1.value, store.arg2.value], createPusher(pbox));
```
To this:
```
return reaction(() => [store.arg1.value, store.arg2.value, store.filterFunction], createPusher(pbox));
```

**Comment by gjulivan** [comment]
> I think it should be fixed on useBasicSync level. Just change line 26 from
> 
> ```
> return reaction(() => [store.arg1.value, store.arg2.value], createPusher(pbox));
> ```
> 
> To this:
> 
> ```
> return reaction(() => [store.arg1.value, store.arg2.value, store.filterFunction], createPusher(pbox));
> ```

but this will trigger onchange for every filter change, of which we don't need.

**Review by iobuhov — DISMISSED** [review]
LGTM

**Review by samuelreichert — DISMISSED** [review]

**Review by leonardomendix — APPROVED** [review]

**Review by iobuhov — APPROVED** [review]

**Pull request merged**
